services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_personal_site_app
    restart: always
    env_file:
      - /opt/pw-secrets/app.env
    expose:
      - "3000"
    depends_on:
      - postgres
    networks:
      - web

  nginx:
    image: nginx:1.27-alpine
    container_name: docker_personal_site_nginx
    restart: always
    depends_on:
      - next-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d:ro
      - /opt/pw-secrets/ssl/godspeedlucip.top_nginx:/etc/nginx/ssl:ro
    networks:
      - web

  postgres:
    image: postgres:16-alpine
    container_name: docker_personal_site_postgres
    restart: always
    env_file:
      - /opt/pw-secrets/db.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - web

networks:
  web:

volumes:
  pg-data:
